[general]
import = [
    "~/.config/alacritty-themes/themes/dark_pride.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[cursor]
style = "Block"

[window]
# dynamic_padding = true
# opacity = 0.7
decorations = "None"

[window.dimensions]
columns = 120
lines = 30
